name: haemosphere
channels:
  - defaults
dependencies:
- itsdangerous=1.1.0
- mako=1.1.4
- nose=1.3.7
- pandas=0.24.2
- plotly=4.14.3
- pytables=3.5.2
- python>=2.6,<3
- rpy2=2.8.6
- selenium=3.141.0
- scipy=1.1.0
- sqlalchemy=1.3.12
- transaction=2.4.0
- pygments=2.5.2
- waitress=1.1.0
- pip
- r=3.4
- r-base=3.4
- numpy=1.14.5